name: Test
on:
  pull_request:
  push:
  schedule: [{ cron: "0 0 10 * *" }] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:
permissions: {}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with: { npm: false }
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  super-lint:
    permissions: { contents: read, packages: read, statuses: write }
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - actions
          - homebrew-nodenv
          - jetbrains-npm
          # - node-build
          - node-build-prerelease
          - node-build-update-defs
          # - nodenv
          # - nodenv-aliases
          - nodenv-default-packages
          - nodenv-each
          - nodenv-env
          - nodenv-installer
          - nodenv-man
          - nodenv-npm-migrate
          - nodenv-nvmrc
          # - nodenv-package-json-engine
          - nodenv-package-rehash
          # - nodenv-update
          - nodenv-vars
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: nodenv/${{ matrix.repo }}
          persist-credentials: false
      - uses: super-linter/super-linter/slim@12562e48d7059cf666c43a4ecb0d3b5a2b31bd9e # v8.4.0
        env:
          USE_FIND_ALGORITHM: true # workaround superlinter
          ### below here should match our reusable test workflow config
          GITHUB_TOKEN: ${{ github.token }}
          BASH_EXEC_IGNORE_LIBRARIES: true # superlinter bug #5731
          FILTER_REGEX_EXCLUDE: node_modules
          VALIDATE_BIOME_FORMAT: false # conflicts with prettier
          VALIDATE_BIOME_LINT: false # conflicts with prettier
          VALIDATE_GIT_COMMITLINT: false # commitlint is bad
          VALIDATE_JSCPD: false # too prone to false-positives
