name: Test
on:
  pull_request:
  push:
  schedule: [{ cron: "0 0 10 * *" }] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:
permissions: {}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with: { npm: false }
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  super-lint:
    permissions: { contents: read, packages: read, statuses: write }
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - node-build-prerelease
          - homebrew-nodenv
          - node-build
          - nodenv-nvmrc
          - nodenv-package-rehash
          - nodenv
          - nodenv-vars
          - nodenv-update
          - nodenv-package-json-engine
          - nodenv-npm-migrate
          - nodenv-man
          - nodenv-installer
          - nodenv-env
          - nodenv-each
          - nodenv-default-packages
          - nodenv-aliases
          - node-build-update-defs
          - jetbrains-npm
          - actions
    steps:
      - uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with: { egress-policy: audit }
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          repository: nodenv/${{ matrix.repo }}
      - uses: super-linter/super-linter/slim@5119dcd8011e92182ce8219d9e9efc82f16fddb6 # v8.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BASH_EXEC_IGNORE_LIBRARIES: true # superlinter bug
          FILTER_REGEX_EXCLUDE: node_modules
          VALIDATE_JSCPD: false # jscpd is false-positive prone and generally not useful
