name: Sync Default Branch
on: workflow_call
permissions: {}

jobs:
  default-branch:
    if: github.ref_name == github.event.repository.default_branch
    permissions: { contents: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with: { egress-policy: audit }
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: git push --force origin HEAD:refs/heads/master
